### ISSUE TITLE
chore: Use of system preupgrade and postupgrade

### ISSUE THREAD

**Issue by davidp94** [rckprtr/dfx-backup-restore#1]
https://github.com/rckprtr/dfx-backup-restore/blob/2dc9beca2d7c19e6277c197fa35907c889898f90/src/phone-book/Main.mo#L32

Why not using the [preupgrade and postupgrade](https://sdk.dfinity.org/docs/language-guide/upgrades.html#_preupgrade_and_postupgrade_system_methods) system calls?

**Comment by rckprtr** [comment]
This was created to extract your state from the IC.

**Comment by davidp94** [comment]
makes total sense  👍
